[tox]
minversion = 3.18.0
envlist = py3,pep8
skipsdist = True
ignore_basepython_conflict = True

[testenv]
basepython = python3
usedevelop = True
setenv =
    PYTHONWARNINGS=default::DeprecationWarning
    DJANGO_SETTINGS_MODULE=openstack_dashboard.test.settings
    PIP_CONSTRAINT={toxinidir}/build-constraints.txt
deps =
    -c{env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/2024.1}
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/test-requirements.txt
commands = stestr run {posargs}

[testenv:pep8]
usedevelop = False
deps = -r{toxinidir}/test-requirements.txt
commands = flake8 {posargs}

[testenv:venv]
commands = {posargs}

[flake8]
# E123, E125 skipped as they are invalid PEP-8.
# W504 skipped, conflicts with W503; the OpenStack style picks W503.
show-source = True
ignore = E123,E125,W504
builtins = _
exclude = .git,.tox,.venv,venv,dist,doc,*egg,*egg-info,build,.omc,.eggs
